FROM python:3.8-bullseye AS builder

RUN apt-get update  \
    && apt-get install curl build-essential ca-certificates tzdata net-tools pkg-config libssl-dev openssl -y \
    && curl https://sh.rustup.rs -sSf | sh -s -- --no-modify-path --default-toolchain none -y \
    && $HOME/.cargo/bin/rustup default stable \
    && $HOME/.cargo/bin/rustc --version

RUN pip install torch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1

# ENV PATH ~/.cargo/bin:$PATH
WORKDIR /app
COPY . .

ENV LIBTORCH=/usr/local/lib/python3.8/site-packages/torch
ENV DYLD_LIBRARY_PATH=${LIBTORCH}/lib 
ENV LD_LIBRARY_PATH=${LIBTORCH}/lib:$LD_LIBRARY_PATH 

RUN ~/.cargo/bin/cargo build --release  
