FROM public.ecr.aws/bitnami/pytorch:1.13.1-debian-11-r33 AS builder

USER root

RUN apt-get update  \
    && apt-get install curl build-essential ca-certificates tzdata net-tools pkg-config libssl-dev openssl -y \
    && curl https://sh.rustup.rs -sSf | sh -s -- --no-modify-path --default-toolchain none -y \
    && $HOME/.cargo/bin/rustup default stable \
    && $HOME/.cargo/bin/rustc --version

ENV PATH $HOME/.cargo/bin:$PATH

COPY . .

ENV LIBTORCH=/opt/bitnami/python/lib/python3.8/site-packages/torch
ENV DYLD_LIBRARY_PATH=${LIBTORCH}/lib
ENV LD_LIBRARY_PATH=${LIBTORCH}/lib:$LD_LIBRARY_PATH


#RUN rustup target add x86_64-unknown-linux-musl
#--target=x86_64-unknown-linux-musl

# RUN rustup target add x86_64-unknown-linux-gnu

RUN cargo build --release 